### ISSUE TITLE
Update to latest nexus version and drop graphql v14 support

### ISSUE THREAD

**Issue by Sytten** [Sytten/nexus-shield#121]
I will update the framework to the latest nexus versions, but that means I must drop support for graphql v14 since that is what they did in nexus.

**Comment by lewebsimple** [comment]
Any ETA on this ?

**Comment by Sytten** [comment]
Hum thanks for reminding me, I will try to do it sometime this week since I finished my other side project

**Comment by Sytten** [comment]
Should be fine now. I kept v14 for now.

**Comment by lewebsimple** [comment]
Any chance you could release this in v1.1.2 soon ?

**Comment by Sytten** [comment]
It should be in v1.1.1 already, are you hitting a bug?

**Comment by lewebsimple** [comment]
@Sytten nevermind .. wrong repo #brainfart
