### ISSUE TITLE
Update peer dependencie to GraphQL 16 & Nexus 1.2

### ISSUE THREAD

**Issue by haleksandre** [Sytten/nexus-shield#414]
Is it possible to update the peer dependencies of to include GraphQL 16 & Nexus 1.2?

Seems the only reason that #406 fails is because of Nexus 1.1 (nexus@latest) NexusGraphQLSchema doesn't match GraphQL 16 GraphQLSchema. Nexus release a pre-release 1.2 (nexus@next) which takes care of this issue. If you have the time & comfortable, could you make a pre-release yourself with Nexus pre-release version in your peer dependencies?

I've force installed your package with Nexus 1.2 & GraphQL 16 & so far everything seem to be working as expected so I don't think you'd need to modify much except the peer dependencies.

Thanks for your time!

**Comment by Sytten** [comment]
Hey I dont have the workflow to pre-release so I will most likely wait for the nexus release and do a sweep of upgrades at the same time. Do feel free to ping me once they release 1.2

**Comment by Sytten** [comment]
Ha thanks for notifying, I am not in the JS world anymore so I didnt catch it. I will update it!

**Comment by Sytten** [comment]
I published v2.2.0 but its not showing un npm yet (unsure why seems like something is broken on their side), I will circle back tomorrow to update the examples.

**Comment by Sytten** [comment]
Latest version should be all good, I also updated the examples
